---
AWSTemplateFormatVersion: "2010-09-09"
Description: template for SNS topic creation and subscription.

Parameters:
  Env:
    Type: String
    AllowedValues: 
      - dev
      - stg
      - prod

Mappings:
  EnvConfig:
    dev:
      EmailAddress1: abimbolaabiodun6@gmail.com
    stg:
      EmailAddress1: abimbolaabiodun6@gmail.com
    prod:
      EmailAddress1: abimbolaabiodun6@gmail.com

Resources:
  FailureSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub project-hie-analytics-ingestion-failure-alerts-${Env}
      DisplayName: !Sub Project Hie Analytics Ingestion Failure Alerts ${Env}
    
  FailureEmailSubscription1:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref FailureSNSTopic
      Protocol: email
      Endpoint: !FindInMap [EnvConfig, !Ref Env, EmailAddress1]
  
Outputs:
  SNSTopicArn:
    Description: "ARN of the SNS topic for ingestion failure alerts"
    Value: !Ref FailureSNSTopic
    Export: 
      Name: !Sub project-hie-analytics-ingestion-failure-alerts-sns-topic-arn-${Env}
    
  SNSTopicName:
    Description: "Name of the SNS topic for ingestion failure alerts"
    Value: !GetAtt FailureSNSTopic.TopicName
    Export: 
      Name: !Sub project-hie-analytics-ingestion-failure-alerts-sns-topic-name-${Env}
