---
AWSTemplateFormatVersion: "2010-09-09"
Description: This template creates an SNS topic for ingestion failure alerts and a Lambda function to publish messages to the topic. 
  
Parameters:
  Env:
    Type: String
    AllowedValues: 
      - dev
      - stg
      - prod
  
Mappings:
  EnvConfig:
    dev:
      EmailAddress1: Abimbola.abiodun@va.gov
    stg:
      EmailAddress1: abimbolaabiodun6@gmail.com
    prod:
      EmailAddress1: 123@example.com
  
Resources:
  IngestionFailureSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub project-hie-analytics-ingestion-failure-alerts-${Env}
      DisplayName: !Sub Ingestion Failure Alerts ${Env}

  IngestionFailureEmailSubscription1:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref IngestionFailureSNSTopic
      Protocol: email
      Endpoint: !FindInMap 
        - EnvConfig
        - !Ref Env
        - EmailAddress1

Outputs:
  OperationalSNSTopicArn:
    Description: "ARN of the SNS topic for ingestion failure alerts"
    Value: !Ref IngestionFailureSNSTopic
    Export: 
      Name: !Sub project-hie-analytics-ingestion-failure-alerts-sns-topic-arn-${Env}
