AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for the admin partner registry exports

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, stg, prod]

Resources:

  # Admin Registry Bucket
  AdminRegistryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub project-hi-analytics-admin-registry-bucket-${Env}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: tenant:CKID
          Value: "2598"
        - Key: tenant:VAECID
          Value: "AWG20251201001"
        - Key: va_vasi_id
          Value: "2238"
        - Key: Name
          Value: !Sub project-hi-analytics-admin-registry-bucket-${Env}
        - Key: Purpose
          Value: admin-registry



Outputs:

  AdminRegistryBucketArn:
    Description: ARN for Admin Registry bucket
    Value: !GetAtt AdminRegistryBucket.Arn
    Export:
      Name: !Sub Admin-Registry-Bucket-Arn-${Env}
