---
AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Roles Stack

Parameters:
  Env:
    Type: String
    AllowedValues:
    - dev
    - stg
    - prod

Resources:
  IAMRolehieTransferFamilyUploadOnly:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: tenant:CKID
          Value: "2598"
        - Key: tenant:VAECID
          Value: "AWG20251201001"
        - Key: va_vasi_id
          Value: "2238"
      RoleName: !Sub project-hie-analytics-transfer-family-upload-only-role-${Env}
      Path: /project/
      PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/vaec/project-admin
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub project-hie-analytics-upload-s3-policy-${Env}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:ListBucket
                Resource: !Sub arn:aws-us-gov:s3:::project-hie-analytics-oraclehealth-documents-${Env}
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub arn:aws-us-gov:s3:::project-hie-analytics-oraclehealth-documents-${Env}/*
  
  IAMRolehieTransferfamilys3uploadrole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: tenant:CKID
          Value: "2598"
        - Key: tenant:VAECID
          Value: "AWG20251201001"
        - Key: va_vasi_id
          Value: "2238"

      RoleName: !Sub project-hie-analytics-transfer-family-s3-upload-role-${Env}
      Path: /project/
      PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/vaec/project-admin
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: !Sub project-hie-analytics-transfer-family-s3-upload-policy-${Env}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowBucketAccess
                Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                Resource: !Sub arn:${AWS::Partition}:s3:::project-hie-analytics-oraclehealth-documents-${Env}

              - Sid: AllowObjectUploadAccess
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:AbortMultipartUpload
                  - s3:ListMultipartUploadParts
                Resource: !Sub arn:${AWS::Partition}:s3:::project-hie-analytics-oraclehealth-documents-${Env}/*
  
  IAMRolehieLambdaFullAccess:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub project-hie-analytics-lambda-full-access-role-${Env}
      Tags:
        - Key: tenant:CKID
          Value: "2598"
        - Key: tenant:VAECID
          Value: "AWG20251201001"
        - Key: va_vasi_id
          Value: "2238"
      Path: /project/
      PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/vaec/project-admin

      ManagedPolicyArns:
        - arn:aws-us-gov:iam::aws:policy/CloudWatchFullAccess
        - arn:aws-us-gov:iam::aws:policy/AmazonS3FullAccess
        - arn:aws-us-gov:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws-us-gov:iam::aws:policy/SecretsManagerReadWrite
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
            
      Policies:
        - PolicyName: !Sub project-hie-analytics-lambda-dlq-policy-${Env}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueAttributes
                Resource: "*"

        - PolicyName: !Sub project-hie-analytics-lambda-invoke-notification-${Env}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:project-hie-analytics-process-notification-${Env}

  IAMRolehieInsertionLambdaFullAccess:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub project-hie-insertion-lambda-full-access-role-${Env}
      Tags:
        - Key: tenant:CKID
          Value: '2598'
        - Key: tenant:VAECID
          Value: AWG20251201001
        - Key: va_vasi_id
          Value: '2238'
      Path: 
      PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/vaec/project-admin

      ManagedPolicyArns:
        - arn:aws-us-gov:iam::aws:policy/CloudWatchFullAccess
        - arn:aws-us-gov:iam::aws:policy/AmazonS3FullAccess
        - arn:aws-us-gov:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws-us-gov:iam::aws:policy/SecretsManagerReadWrite

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: lambda-hie-dlq-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: '*'

                
  IAMRolehieEC2SSMSessionRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: tenant:CKID
          Value: "2598"
        - Key: tenant:VAECID
          Value: "AWG20251201001"
        - Key: va_vasi_id
          Value: "2238"
      RoleName: !Sub project-hie-analytics-ec2-ssm-role-${Env}
      Path: /project/
      PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/vaec/project-admin
      ManagedPolicyArns:
        - arn:aws-us-gov:iam::aws:policy/AmazonSSMManagedInstanceCore
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

Outputs:
  LambdaRoleArn:
    Value: !GetAtt IAMRolehieLambdaFullAccess.Arn
    Export:
      Name: !Sub project-hie-analytics-lambda-full-access-role-arn-${Env}
      
  LambdaInsertionRoleArn:
    Value: !GetAtt IAMRolehieInsertionLambdaFullAccess.Arn
    Export:
      Name: !Sub project-hie-analytics-lambda-insertion-role-arn-${Env}

  EC2SSMRoleArn:
    Value: !GetAtt IAMRolehieEC2SSMSessionRole.Arn
    Export:
      Name: !Sub project-hie-analytics-ec2-ssm-role-arn-${Env}

  TransferFamilyUploadOnlyRoleArn:
    Value: !GetAtt IAMRolehieTransferFamilyUploadOnly.Arn
    Export:
      Name: !Sub project-hie-analytics-transfer-family-upload-only-role-arn-${Env}

  TransferFamilyRoleArn:
    Value: !GetAtt IAMRolehieTransferfamilys3uploadrole.Arn
    Export:
      Name: !Sub project-hie-analytics-transfer-family-s3-upload-role-arn-${Env}
